format = """
$battery\
$hostname\
$directory\
$git_branch\
$git_status\
$character\
"""

[battery]
full_symbol = "•"
charging_symbol = "⇡"
discharging_symbol = "⇣"

[username]
show_always = true
style_user = "cyan bold"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bright-cyan bold"
format = "[$hostname]($style) "

[directory]
style = "white"
truncate_to_repo = false

[git_branch]
format = "[$branch]($style)"
#style = "bright-black"
style = "#82bfde"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](bright-yellow) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[character]
success_symbol = "[λ](white)"
error_symbol = "[λ](red)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
python_binary = 'python3'
