#!/bin/bash

which hub &> /dev/null
if [[ $? -eq 0 ]]; then
  alias git=hub
  alias gpr="git pull-request"
  hub_completion=${GOPATH}/src/github.com/github/hub/etc/hub.bash_completion.sh
  if [ -a $hub_completion ]; then
    source $hub_completion
  fi
fi

alias pfiles="lsof -a -p"
alias ll="ls -lh"
alias ports-listening="netstat -an -ptcp | grep LISTEN"
