# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

# Get custom env vars
source ${HOME}/.bash_custom/bash_vars
source ${HOME}/.bash_custom/*
