# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

# Get custom env vars
PS1='[\u@\h] \w\[\033[33m\]$(__git_ps1)\[\033[00m\]\$ '
GIT_PS1_SHOWDIRTYSTATE=true

source ${HOME}/.bash_custom/git-completion.sh
source ${HOME}/.bash_custom/env_vars

for $plugin in $(ls ${HOME}/.bash_custom/plugins);
do
  source ${HOME}/.bash_custom/plugins/${plugin}
done
